[package]
name = "machine_interface"
version = "0.1.0"
edition = "2021"

[build-dependencies]
cmake = "0.1"

[dev-dependencies]
criterion = "0.4"
# need to lock this to older version, because morello does not yet have rustc 1.6
regex = "1.7.1"

[dependencies]
dandelion_commons = { path = "../dandelion_commons" }
# FFI dependencies
libc = "0.2"
core_affinity = "0.8"
futures = "0.3"
tokio = { version = "1", features = ["full"] }

# disable benchmarks in library, to not run all unit tests on every benchmark
# also needs to be disabled for criterion flags to work that are not available for tests
[lib]
bench = false

[[bench]]
name = "cheri_benchmark"
harness = false