[package]
name = "machine_interface"
version = "0.1.0"
edition = "2021"

[build-dependencies]
cmake = "0.1"

[dependencies]
# FFI dependencies
libc = "0.2"
core_affinity = "0.8"
shared_memory = { git = "https://github.com/elast0ny/shared_memory" }
